#!/usr/bin/sh

sxhkd -c $HOME/.config/bspwm/sxhkdrc &
~/.config/polybar/launch.sh --docky
mpv --no-video $HOME/.local/share/win/startup.wav &
picom &
dunst &
pkill volumeicon
pkill nm-applet
volumeicon &
nm-applet &
dex-autostart --autostart --enviornment bspwm
#feh --bg-fill $HOME/.config/dwm/bg.jpg &
waypaper --restore

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		70
bspc config bottom_padding	18
bspc config left_padding	18
bspc config right_padding	18
bspc config single_monocole	false


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier	 mod4
bspc config pointer_action1	 move
bspc config pointer_action2	 resize_side
bspc config pointer_action3	 resize_corner

bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors   true

bspc config normal_border_color		"#222222"
bspc config active_border_color		"#444444"
bspc config focused_border_color	"#770000"
bspc config presel_feedback_color	"#770000"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Galculator state=floating
bspc rule -a Emacs state=tiled
bspc rule -a feh state=floating
bspc rule -a Arandr state=floating
